### ISSUE TITLE
Suggestion - remove fall detector from player death script

### ISSUE THREAD

**Issue by nbakotic** [nbakotic/GameProject#31]
Since in the random generation scene the player can't fall off the map, there is no need to check for player falling off. Instead, smaller traps that deal health damage could serve a similar purpose. This will prevent the player death script from throwing an unassigned reference exception in scenes without a fall detector that isn't used anyways.

**Comment by aZina0** [comment]
I agree. I invoke @AKStifter for his input as he added this functionality.

**Comment by AKStifter** [comment]
Ok, the fall detector will be removed.

**Comment by AKStifter** [comment]
Fall detector was removed from the test scene and player death script.
