### ISSUE TITLE
player combat system

### ISSUE THREAD

**Issue by nbakotic** [nbakotic/GameProject#5]

**Comment by AKStifter** [comment]
A bug appears where if you jump on top of the bullet you can't jump again. The best solution would probably be to despawn the bullet on collision.

**Comment by aZina0** [comment]
> A bug appears where if you jump on top of the bullet you can't jump again. The best solution would probably be to despawn the bullet on collision.

Committed c24ad6ccc559495df4e73485ea750c4c9bb7f6cc which adds option to despawn projectiles on impact (on by default).
